- name: Update apt packages
  apt:
    update_cache: yes

- name: Install required  packages
  apt: 
    name: "{{ apt_packages }}"
    state: present

- name: Clone the app repo
  git:
    repo: "{{ git_repo }}"
    dest: "/usr/local/slice"

- name: Install pip requirments
  pip:
    requirements: "{{ application_root_dir }}/requirements.txt"
    executable: pip3

- name: Copy webapp config file
  template:
    src: config.json.j2
    dest: "{{ application_root_dir }}/config.json"

- name: Create service file
  template:
    src: mywebapp.service.j2
    dest: /etc/systemd/system/mywebapp.service
  notify: restart mywebapp server 
